### ISSUE TITLE
Invalid config bug that disables plugin

### ISSUE THREAD

**Issue by Swirren** [INotSleep/FishingSpots#1]
![image](https://github.com/INotSleep/FishingSpots/assets/64167426/cbfb7a47-2b7e-441c-acdb-03b36f2a235d)

no other info, config has not been changed

**Comment by Swirren** [comment]
just tried again. deleted all files, downloaded new plugin file, same thing

**Comment by INotSleep** [comment]
What software and version do you use? Also send config.yml

**Comment by Swirren** [comment]
Paper 1.20.1, and like I mentioned above, I made no changes to the config. It’s the same as the one in the Spigot description

**Comment by INotSleep** [comment]
I found issue, i just forgot to change error description. You need to add rewards to be able catch the fish

**Comment by INotSleep** [comment]
Instruction for creations are in rewards.yml and on spigot page in "Configuration and Examples"

If that resolves your issue, please close it

**Comment by Swirren** [comment]
Thanks, glad that was clarified.
